# Generated by Django 5.2.15 on 2026-06-18 01:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdditionalDeliveryFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(default="default_key", unique=True)),
                ("zone_2", models.FloatField(default=1.0)),
                ("zone_3", models.FloatField(default=1.0)),
                ("zone_4", models.FloatField(default=1.0)),
                ("zone_5", models.FloatField(default=1.0)),
                ("zone_6", models.FloatField(default=1.0)),
                ("zone_7", models.FloatField(default=1.0)),
                ("zone_8", models.FloatField(default=1.0)),
                ("weighted_average", models.FloatField(default=0)),
                ("conditions", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "B.[Dataset_1] Additional Delivery Charge",
                "db_table": "additional_delivery_fee",
            },
        ),
        migrations.CreateModel(
            name="AmazonFulfillmentFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(unique=True)),
                ("category", models.CharField(max_length=50)),
                ("product_tier_1", models.CharField(max_length=50)),
                ("product_tier_2", models.CharField(max_length=50)),
                ("shipping_wgt_lbs_opr", models.CharField(max_length=2)),
                ("shipping_wgt_lbs_val", models.FloatField()),
                ("fulfillment_fee", models.FloatField()),
                ("extra_fee", models.FloatField(default=0)),
                (
                    "condition",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "B.[Amz_3_1] Amazon Fulfillment Fee",
                "db_table": "amazon_fulfillment_fee",
            },
        ),
        migrations.CreateModel(
            name="AmazonInboundFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(unique=True)),
                ("product_tier_1", models.CharField(max_length=50)),
                ("product_tier_2", models.CharField(max_length=50)),
                ("shipping_wgt_lbs_opr", models.CharField(max_length=2)),
                ("shipping_wgt_lbs_val", models.FloatField()),
                ("inbound_fee_Med", models.FloatField(blank=True, null=True)),
                ("inbound_fee_MAX", models.FloatField(blank=True, null=True)),
                ("inbound_fee_min", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "B.[Amz_3_2] Amazon Inbound Fee",
                "db_table": "amazon_inbound_fee",
            },
        ),
        migrations.CreateModel(
            name="AmazonProductTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(unique=True)),
                ("product_tier_1", models.CharField(max_length=50)),
                ("product_tier_2", models.CharField(max_length=50)),
                ("shipping_wgt_lbs_opr", models.CharField(max_length=2)),
                ("shipping_wgt_lbs_val", models.FloatField()),
                ("longest_inch_opr", models.CharField(max_length=2)),
                ("longest_inch_val", models.FloatField()),
                ("median_inch_opr", models.CharField(max_length=2)),
                ("median_inch_val", models.FloatField()),
                ("shortes_inch_opr", models.CharField(max_length=2)),
                ("shortes_inch_val", models.FloatField()),
                (
                    "lengirth_inch_opr",
                    models.CharField(blank=True, default=None, max_length=2, null=True),
                ),
                (
                    "lengirth_inch_val",
                    models.FloatField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "B.[Amz_3_0] Amazon Product Tier",
                "db_table": "amazon_product_tier",
            },
        ),
        migrations.CreateModel(
            name="AmazonReferralFeeComplex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(unique=True)),
                ("category", models.CharField(max_length=100)),
                ("price_range_operator", models.CharField(max_length=2)),
                ("price_range_value", models.FloatField()),
                ("referral_fee_rate", models.FloatField()),
                ("minimum_fee", models.FloatField(default=0)),
                ("extra_fee", models.FloatField(default=0)),
                ("type", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "B.[Amz_2] Amazon Referral Fee Complex",
                "db_table": "amazon_referral_fee_complex",
            },
        ),
        migrations.CreateModel(
            name="AmazonReferralFeeSimple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(unique=True)),
                ("category", models.CharField(max_length=100)),
                ("referral_fee_rate", models.FloatField()),
                ("minimum_fee", models.FloatField(default=0)),
                ("extra_fee", models.FloatField(default=0)),
            ],
            options={
                "verbose_name_plural": "B.[Amz_1] Amazon Referral Fee Simple",
                "db_table": "amazon_referral_fee_simple",
            },
        ),
        migrations.CreateModel(
            name="CalculationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_pallets", models.IntegerField()),
                ("products_per_carton", models.IntegerField()),
                ("cartons_per_pallet", models.IntegerField()),
                ("product_width", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product_height",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "product_length",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "product_weight",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "cost_per_product",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("amazon_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amazon_category", models.CharField(max_length=100)),
                ("walmart_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("walmart_category", models.CharField(max_length=100)),
                (
                    "own_shop_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("own_aov", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_products", models.IntegerField()),
                (
                    "estimated_price_own",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "estimated_price_amz",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "estimated_price_wmt",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("product_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "freight_charges",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "customs_charges",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "devanning_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "declaration_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("port_charges", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bol_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "receiving_charges",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_export_and_associated_costs",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "export_and_associated_costs_per_product",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "profit_after_arrival_own",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "profit_after_arrival_amz",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "profit_after_arrival_wmt",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "fulfillment_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "delivery_cost_own",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amazon_referral_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amazon_fulfillment_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amazon_storage_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amazon_inbound_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amazon_fba_logistics_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amazon_fba_receiving_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "walmart_referral_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "walmart_fulfillment_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "walmart_storage_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "walmart_wfs_logistics_fee",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "walmart_wfs_receiving_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("own_result", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amz_result", models.DecimalField(decimal_places=2, max_digits=10)),
                ("wmt_result", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "X.[Admin] User Calculation Logs",
                "db_table": "user_calculation_log",
            },
        ),
        migrations.CreateModel(
            name="CommonCenterOutboundFee",
            fields=[
                ("key", models.AutoField(primary_key=True, serialize=False)),
                ("so", models.CharField(max_length=50)),
                ("no_of_box", models.IntegerField()),
                ("unit", models.IntegerField()),
                ("weight_kg", models.FloatField()),
                ("fulfillment_fee", models.FloatField()),
                ("per_box", models.FloatField()),
                ("per_unit", models.FloatField()),
                ("per_kg", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "A.[Dataset_3] Common Center Outbound Fees",
                "db_table": "common_center_outbound_fee",
            },
        ),
        migrations.CreateModel(
            name="CommonStorageFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(unique=True)),
                ("type", models.CharField(max_length=50)),
                (
                    "prd_tier",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "mon_opr",
                    models.CharField(blank=True, default=None, max_length=2, null=True),
                ),
                ("mon_val", models.FloatField(blank=True, default=None, null=True)),
                ("mon_period_1", models.IntegerField()),
                ("period_1_val", models.FloatField()),
                ("mon_period_2", models.IntegerField()),
                ("period_2_val", models.FloatField()),
                ("mon_weighted_avg", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "A.[Dataset_5] Common Storage Fee",
                "db_table": "common_storage_fee",
            },
        ),
        migrations.CreateModel(
            name="CompanyBoxFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(unique=True)),
                ("type", models.CharField(max_length=50)),
                ("longest", models.FloatField()),
                ("median", models.FloatField()),
                ("shortest", models.FloatField()),
                ("unit_price", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "A.[Dataset_7] Company Box Fee",
                "db_table": "company_box_fee",
            },
        ),
        migrations.CreateModel(
            name="DeliveryIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(unique=True)),
                ("date", models.DateField()),
                ("delivery_idx_teu", models.FloatField()),
                ("real_per_idx_teu", models.FloatField()),
                ("delivery_real_teu", models.FloatField()),
                ("delivery_idx_feu", models.FloatField()),
                ("real_per_idx_feu", models.FloatField()),
                ("delivery_real_feu", models.FloatField()),
                ("avg_del_per_cbm", models.FloatField()),
                ("del_per_cbm_1", models.FloatField()),
                ("del_per_cbm_2", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_3", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_4", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_5", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_6", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_7", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_8", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_9", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_10", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_11", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_12", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_13", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_14", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_15", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_16", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_17", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_18", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_19", models.FloatField(blank=True, null=True)),
                ("del_per_cbm_20", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "A.[Dataset_2_I] Delivery Indices",
                "db_table": "delivery_indices",
                "ordering": ["-key"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryIndicesSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(default=1, unique=True)),
                ("recent_teu", models.FloatField(blank=True, null=True)),
                ("avg_real_per_idx_teu", models.FloatField(blank=True, null=True)),
                ("recent_feu", models.FloatField(blank=True, null=True)),
                ("avg_real_per_idx_feu", models.FloatField(blank=True, null=True)),
                ("recent_3_months_avg_cbm", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "A.[Dataset_2_O] Delivery Indices Summary",
                "db_table": "delivery_indices_summary",
            },
        ),
        migrations.CreateModel(
            name="GroundService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(default="default_key", unique=True)),
                ("lbs", models.FloatField()),
                ("zone_2", models.FloatField()),
                ("zone_3", models.FloatField()),
                ("zone_4", models.FloatField()),
                ("zone_5", models.FloatField()),
                ("zone_6", models.FloatField()),
                ("zone_7", models.FloatField()),
                ("zone_8", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "A.[Dataset_4_I] Ground Service Charges",
                "db_table": "ground_service",
            },
        ),
        migrations.CreateModel(
            name="ShippingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(unique=True)),
                ("date_of_dept", models.DateField()),
                ("brand", models.CharField(max_length=100)),
                ("po", models.CharField(max_length=100)),
                ("cbm_invoice", models.FloatField()),
                ("cbm_pl", models.FloatField()),
                ("cbm_inv_per_pl", models.FloatField()),
                ("pallet", models.IntegerField()),
                ("local_delivery", models.FloatField()),
                ("delivery_per_cbm_7", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "A.[Dataset_1_I] Shipping Records",
                "db_table": "shipping_records",
                "ordering": ["-key"],
            },
        ),
        migrations.CreateModel(
            name="ShippingRecordsSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(default=1, unique=True)),
                ("avg_cbm_inv_per_pl", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "A.[Dataset_1_O] Shipping Records Summary",
                "db_table": "shipping_records_summary",
            },
        ),
        migrations.CreateModel(
            name="VariableConfigurations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no", models.IntegerField()),
                ("category", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=50)),
                ("value", models.FloatField()),
                ("value_type", models.CharField(max_length=20)),
                (
                    "unit",
                    models.CharField(blank=True, default="-", max_length=20, null=True),
                ),
                (
                    "minimum",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default="-",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "details",
                    models.CharField(
                        blank=True, default="-", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "A.[Dataset_6] Variable Configurations",
                "db_table": "variable_configurations",
            },
        ),
        migrations.CreateModel(
            name="WalmartFulfillmentFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(unique=True)),
                ("product_tier", models.CharField(max_length=50)),
                ("shipping_wgt_lbs_from_opr", models.CharField(max_length=10)),
                ("shipping_wgt_lbs_from_val", models.FloatField()),
                ("shipping_wgt_lbs_to_opr", models.CharField(max_length=10)),
                ("shipping_wgt_lbs_to_val", models.FloatField()),
                ("fulfillment_fee", models.FloatField()),
                ("extra_fee", models.FloatField(blank=True, null=True)),
                (
                    "extra_condition",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "add_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("add_val", models.FloatField(blank=True, null=True)),
                ("add_min_opr", models.CharField(blank=True, max_length=10, null=True)),
                ("add_min_val", models.FloatField(blank=True, null=True)),
                ("add_min_fee", models.FloatField(blank=True, null=True)),
                (
                    "long_in_fr_opr_1",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("long_in_fr_val_1", models.FloatField(blank=True, null=True)),
                (
                    "long_in_to_opr_1",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("long_in_to_val_1", models.FloatField(blank=True, null=True)),
                ("long_in_add_1", models.FloatField(blank=True, null=True)),
                ("med_in_opr", models.CharField(blank=True, max_length=10, null=True)),
                ("med_in_val", models.FloatField(blank=True, null=True)),
                ("med_in_add", models.FloatField(blank=True, null=True)),
                (
                    "lg_in_fr_opr_1",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("lg_in_fr_val_1", models.FloatField(blank=True, null=True)),
                (
                    "lg_in_to_opr_1",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("lg_in_to_val_1", models.FloatField(blank=True, null=True)),
                ("lg_in_add_1", models.FloatField(blank=True, null=True)),
                (
                    "long_in_fr_opr_2",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("long_in_fr_val_2", models.FloatField(blank=True, null=True)),
                (
                    "long_in_to_opr_2",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("long_in_to_val_2", models.FloatField(blank=True, null=True)),
                ("long_in_add_2", models.FloatField(blank=True, null=True)),
                (
                    "lg_in_fr_opr_2",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("lg_in_fr_val_2", models.FloatField(blank=True, null=True)),
                (
                    "lg_in_to_opr_2",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("lg_in_to_val_2", models.FloatField(blank=True, null=True)),
                ("lg_in_add_2", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "C.[Wmt_3] Walmart Fulfillment Fee",
                "db_table": "walmart_fulfillment_fee",
            },
        ),
        migrations.CreateModel(
            name="WalmartReferralFeeComplex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(unique=True)),
                ("category", models.CharField(max_length=50)),
                ("price_range_operator", models.CharField(max_length=2)),
                ("price_range_value", models.FloatField()),
                ("referral_fee_rate", models.FloatField()),
                ("type", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "C.[Wmt_2] Walmart Referral Fee Complex",
                "db_table": "walmart_referral_fee_complex",
            },
        ),
        migrations.CreateModel(
            name="WalmartReferralFeeSimple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(unique=True)),
                ("category", models.CharField(max_length=50)),
                ("referral_fee_rate", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "C.[Wmt_1] Walmart Referral Fee Simple",
                "db_table": "walmart_referral_fee_simple",
            },
        ),
        migrations.CreateModel(
            name="WeightedGroundService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(default="default_key", unique=True)),
                ("lbs", models.FloatField()),
                ("weighted_zone_2", models.FloatField()),
                ("weighted_zone_3", models.FloatField()),
                ("weighted_zone_4", models.FloatField()),
                ("weighted_zone_5", models.FloatField()),
                ("weighted_zone_6", models.FloatField()),
                ("weighted_zone_7", models.FloatField()),
                ("weighted_zone_8", models.FloatField()),
                ("weighted_zone_average", models.FloatField(default=0)),
            ],
            options={
                "verbose_name_plural": "A.[Dataset_4_O] Weighted Ground Service Charges",
                "db_table": "weighted_ground_service",
            },
        ),
        migrations.CreateModel(
            name="ZoneWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.IntegerField(unique=True)),
                (
                    "zone_2_weight",
                    models.FloatField(default=1.0, verbose_name="Zone 2 Weight"),
                ),
                (
                    "zone_3_weight",
                    models.FloatField(default=1.0, verbose_name="Zone 3 Weight"),
                ),
                (
                    "zone_4_weight",
                    models.FloatField(default=1.0, verbose_name="Zone 4 Weight"),
                ),
                (
                    "zone_5_weight",
                    models.FloatField(default=1.0, verbose_name="Zone 5 Weight"),
                ),
                (
                    "zone_6_weight",
                    models.FloatField(default=1.0, verbose_name="Zone 6 Weight"),
                ),
                (
                    "zone_7_weight",
                    models.FloatField(default=1.0, verbose_name="Zone 7 Weight"),
                ),
                (
                    "zone_8_weight",
                    models.FloatField(default=1.0, verbose_name="Zone 8 Weight"),
                ),
                ("discount", models.FloatField(default=0)),
            ],
            options={
                "verbose_name_plural": "A.[Dataset_4_X] Zone Weights",
                "db_table": "zone_weight",
                "ordering": ["-key"],
            },
        ),
    ]
