# Generated by Django 5.2.15 on 2026-06-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hc_calc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationlog",
            name="memo",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="calculationlog",
            name="product_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
